1.NAME OF THE EMPLOYEE AND HIS LOCATION OF ALL THE
EMPLOYEES .

1.SELECT ENAME,LOC
FROM EMP,DEPT
WHERE EMP.DEPTNO=DEPT.DEPTNO;

2.WAQTD DNAME AND SALARY FOR ALL THE EMPLOYEE
WORKING IN ACCOUNTING.


2.SELECT DNAME,SAL
FROM EMP,DEPT
WHERE EMP.DEPTNO=DEPT.DEPTNO AND DNAME='ACCOUNTING';

3.WAQTD DNAME AND ANNUAL SALARY FOR ALL
EMPLOYEES WHOS SALARY IS MORE THAN 2340

3. SELECT DNAME,SAL*12
 FROM EMP,DEPT
 WHERE EMP.DEPTNO=DEPT.DEPTNO AND SAL>2340;

4.WAQTD ENAME AND DNAME FOR EMPLOYEES HAVING
CAHARACTER 'A' IN THEIR DNAME.

4.  SELECT ENAME,DNAME
 FROM EMP,DEPT
 WHERE EMP.DEPTNO=DEPT.DEPTNO AND ENAME LIKE '%A%';

5.WAQTD ENAME AND DNAME FOR ALL THE EMPLOYEES
WORKING AS SALESMAN.

5. SELECT ENAME,DNAME
 FROM EMP,DEPT
 WHERE EMP.DEPTNO=DEPT.DEPTNO AND JOB IN 'SALESMAN';

6.WADTD DNAME AND JOB FOR ALL THE EMPLOYEES WHOS
JOB AND DNAME STARTS WITH CHARACTER 'S'.

6.SELECT DNAME,JOB
FROM EMP,DEPT
WHERE EMP.DEPTNO=DEPT.DEPTNO AND DNAME LIKE '%S%' AND JOB LIKE '%S%';

7.WAQTD DNAME AND MGR NO FOR EMPLOYEES
REPORTING TO 7839.

7.SELECT DNAME,MGR
 FROM EMP,DEPT
 WHERE EMP.DEPTNO=DEPT.DEPTNO AND MGR=7839;  

8.WAQTD DNAME AND HIREDATE FOR EMPLOYEES HIRED
AFTER 83 INTO ACCOUNTING OR RESEARCH DEPT.

8.SELECT DNAME,HIREDATE
FROM EMP,DEPT
WHERE EMP.DEPTNO=DEPT.DEPTNO AND HIREDATE >'31-DEC-83' AND DNAME IN ('ACCOUNTING','RESEARCH');

9.WAQTD ENAME AND DNAME OF THE EMPLOYEES WHO
ARE GETTING COMM IN DEPT 10 OR 30.

9. SELECT ENAME,DNAME
 FROM EMP,DEPT
 WHERE EMP.DEPTNO=DEPT.DEPTNO AND COMM IS NOT NULL AND EMP.DEPTNO IN (10,30);

10.WAQTD DNAME AND EMPNO FOR ALL THE EMPLOYEES
WHO 's  EMPNO ARE (7839,7902) AND ARE WORKING IN LOC
NEW YORK.

10.  SELECT DNAME,EMPNO
 FROM EMP,DEPT
 WHERE EMP.DEPTNO=DEPT.DEPTNO AND EMPNO IN (7839,7902) AND LOC ='NEW YORK';

 
