1.WAQTD NUMBER OF EMPLOYEES GETTING SALARY LESS
THAN 2000 IN DEPTNO 10.

  

  
1.SELECT COUNT(*)
FROM EMP
WHERE DEPTNO=10 AND SAL<2000;

2.WAQTD TOTAL SALARY NEEDED TO PAY EMPLOYEES
WORKING AS CLERK.

2.SELECT SUM(SAL)
  FROM EMP
  WHERE JOB ='CLERK';

3.WAQTD AVERAGE SALARY NEEDED TO PAY ALL
EMPLOYEES
  
3.SELECT AVG(SAL)
 FROM EMP;

4.WAQTD NUMBER OF EMPLOYEES HAVING 'A' AS THEIR
FIRST CHARACTER.

4.SELECT COUNT(*)
 FROM EMP
 WHERE ENAME LIKE 'A%';

5.WAQTD NUMBER OF EMPLOYEES WORKING AS CLERK OR
MANAGER.

5.SELECT COUNT (*)
FROM EMP
WHERE JOB IN ('CLERK','MANAGER');

6.WAQTD TOTAL SALARY NEEDED TO PAY EMPLOYEES
HIRED IN FEB.

6.SELECT SUM(SAL)
FROM EMP
WHERE HIREDATE LIKE '%FEB%';

7.WAQTD NUMBER OF EMPLOYEES REPORTING TO 7839 (MGR).

7.SELECT COUNT (*)
FROM EMP
WHERE MGR ='7839';

8.WAQTD NUMBER OF EMPLOYEES GETTING COMISSION IN
DEPTNO 30.

8.SELECT COUNT(COMM)
FROM EMP
WHERE DEPTNO=30;

9.WAQTD AVG SAL , TOTAL SAL , NUMBER OF EMPS AND
MAXIMUM SALARY GIVEN TO EMPLOYEES WORKING AS
PERSIDENT.

9.SELECT AVG(SAL),SUM(SAL),COUNT(*),MAX(SAL)
 FROM EMP
 WHERE JOB = 'PRESIDENT';

10.WAQTD NUMBER OF EMPLOYEES HAVING 'A' IN THEIR
NAMES.

10.SELECT COUNT(*)
FROM EMP
WHERE ENAME LIKE '%A%';

11.WAQTD NUMBER OF EMPS AND TOTAL SALARY NEEDED
TO PAY THE EMPLOYEES WHO HAVE 2 CONSICUTIVE L In their names.

11.SELECT COUNT(*),SUM(SAL)
FROM EMP
WHERE ENAME LIKE '%LL%';

12.WAQTD NUMBER OF DEPARTMENTS PRESENT IN
EMPLOYEE TABLE.

12. SELECT COUNT(DEPTNO)
FROM EMP;

13.WAQTD NUMBER OF EMPLOYEES HAVING CHARACTER 'Z'
IN THEIR NAMES.

13.SELECT COUNT(*)
FROM EMP
WHERE ENAME LIKE '%Z%';

14.WAQTD NUMBER OF EMPLOYEES HAVING '$' IN THEIR
NAMES .

14.SELECT COUNT(*)
FROM EMP
WHERE ENAME LIKE '%$%';

15.WAQTD TOTAL SALARY GIVEN TO EMPLOYEES WORKING
AS CLERK IN DEPT 30.

15.SELECT SUM(SAL)
FROM EMP
WHERE JOB ='CLERK' AND DEPTNO=30;

16.WAQTD MAXIMUM SALARY GIVEN TO THE EMPLOYEES
WORKING AS ANALYST.

16.SELECT MAX(SAL)
 FROM EMP
 WHERE JOB IN 'ANALYST';

17.WAQTD NUMBER OF DISTINCT SALARIES PRESENT IN
EMPLOYEE TABLE.

17.SELECT COUNT (DISTINCT SAL)
FROM EMP;

18.WAQTD NUMBER OF JOBS PRESENT IN EMPLOYEE TABLE.

18.SELECT COUNT(DISTINCT JOB)
 FROM EMP;

19.WATQD AVG SALARY GIVEN TO THE CLERK.

19.SELECT AVG(SAL)
FROM EMP
WHERE JOB IN 'CLERK';

20.WAQTD MINIMUM SALARY GIVEN TO THE EMPLOYEES
WHO WORK IN DEPT 10 AS MANAGER OR A CLERK.

20.SELECT MIN(SAL)
 FROM EMP
 WHERE DEPTNO IN 10 AND JOB IN ('MANAGER','CLERK');





