1. LIST ALL THE EMPLOYEES WHOSE COMMISSION IS
NUL. 

1.SELECT *
 FROM EMP
 WHERE COMM IS NULL;

2. LIST ALL THE EMPLOYEES WHO DON’T HAVE A
REPORTING MANAGER

2.SELECT *
FROM EMP
WHERE MGR IS NULL;

3. LIST ALL THE SALESMEN IN DEPT 30

3.SELECT *
 FROM EMP
 WHERE JOB='SALESMAN'
 AND DEPTNO=30;

4. LIST ALL THE SALESMEN IN DEPT NUMBER 30 AND
HAVING SALARY GREATER THAN 1500

 4.SELECT *
 FROM EMP
 WHERE JOB='SALESMAN'
 AND DEPTNO=30
AND SAL>1500;

5.LIST ALL THE EMPLOYEES WHOSE NAME STARTS
WITH ‘S’ OR ‘A’.

5.SELECT *
FROM EMP
WHERE ENAME LIKE 'S%'
OR ENAME LIKE 'A%';

6. LIST ALL THE EMPLOYEES EXCEPT THOSE WHO ARE
WORKING IN DEPT 10 & 20.

6.SELECT *
FROM EMP
WHERE DEPTNO  NOT IN (10,20);   (EXPECT MEANS IS NOT)

7.LIST THE EMPLOYEES WHOSE NAME DOES NOT START
WITH ‘S’.

7.SELECT ENAME
 FROM EMP
 WHERE ENAME NOT LIKE 'S%';

8.LIST ALL THE EMPLOYEES WHO ARE HAVING
REPORTING MANAGERS IN DEPT 10.

8.SELECT ENAME
FROM EMP
WHERE MGR IS NOT NULL
AND DEPTNO IN 10;

9.LIST ALL THE EMPLOYEES WHOSE COMMISSION IS
NULL AND WORKING AS CLERK.

9. SELECT *
 FROM EMP
 WHERE COMM IS NULL
 AND JOB ='CLERK';

 10. LIST ALL THE EMPLOYEES WHO DON’T HAVE A
REPORTING MANAGER IN DEPTNO 10 OR 30.

 10.SELECT *
 FROM EMP
 WHERE MGR IS NULL
AND DEPTNO IN (10,30);

11. LIST ALL THE SALESMEN IN DEPT 30 WITH SAL MORE
THAN 2450.

11. SELECT *
 FROM EMP
 WHERE JOB ='SALESMAN'
 AND DEPTNO = 30
AND SAL>2450;

12.LIST ALL THE ANALYST IN DEPT NUMBER 20 AND
HAVING SALARY GREATER THAN 2500.

12.SELECT *
 FROM EMP
 WHERE DEPTNO=20
AND SAL>2500;

13.LIST ALL THE EMPLOYEES WHOSE NAME STARTS
WITH ‘M’ OR ‘J’.

13.SELECT *
FROM EMP
WHERE ENAME LIKE 'M%'
OR ENAME LIKE 'J%';

14. LIST ALL THE EMPLOYEES WITH ANNUAL SALARY
EXCEPT THOSE WHO ARE WORKING IN DEPT 30.

14.SELECT ENAME ,SAL*12 AS ANNUAL
 FROM EMP
 WHERE DEPTNO NOT IN 30;

15. LIST THE EMPLOYEES WHOSE NAME DOES NOT END
WITH ‘ES’ OR ‘R’.

15.SELECT *
 FROM EMP
 WHERE ENAME NOT LIKE 'ES%' 
 OR ENAME NOT LIKE 'R';

16. LIST ALL THE EMPLOYEES WHO ARE HAVING
REPORTING MANAGERS IN DEPT 10 ALONG WITH 10%
HIKE IN SALARY.

 16. SELECT ENAME,SAL*1.10 AS ANNUAL_SALARY
FROM EMP
WHERE MGR IS NOT NULL AND DEPTNO IN 30;

17. DISPLAY ALL THE EMPLOYEE WHO ARE
‘SALESMAN’S HAVING ‘E’ AS THE LAST BUT ONE
CHARACTER IN ENAME BUT SALARY HAVING EXACTLY
4 CHARACTER.

18.SELECT *
   FROM EMP
   WHERE JOB = 'SALESMAN'
   AND ENAME LIKE '%E_'
   AND SAL BETWEEN 1000 AND 9999;

18.DISPLAY ALL THE EMPLOYEE WHO ARE JOINED
AFTER YEAR 81.

18. SELECT *
FROM EMP
WHERE HIREDATE > ('31-DEC-81');

19.DISPLAY ALL THE EMPLOYEE WHO ARE JOINED IN
FEB.

19.SELECT *
FROM EMP
WHERE HIREDATE LIKE '%FEB%';

20. LIST THE EMPLOYEES WHO ARE NOT WORKING AS
MANAGERS AND CLERKS IN DEPT 10 AND 20 WITH A
SALARY IN THE RANGE OF 1000 TO 3000.

20.SELECT *
 FROM EMP WHERE JOB NOT IN ('MANAGER','CLERK')
 AND DEPTNO IN (10,20)
 AND SAL BETWEEN 1000 AND 3000;

