1.SELECT *
FROM EMP
WHERE DEPTNO IN (SELECT DEPTNO
FROM DEPT
WHERE LOC='NEWYORK');

2. SELECT EMP.*,SAL+SAL*0.1
 FROM EMP
 WHERE ENAME LIKE '%R';

3. SELECT EMP.*,SAL+SAL*0.1
FROM EMP
WHERE ENAME LIKE '%R';


4.SELECT *
FROM EMP
WHERE SAL LIKE '____';


5. SELECT DNAME
 FROM DEPT
 WHERE DEPTNO IN (SELECT DEPTNO
 FROM EMP
 WHERE ENAME IN ('ADAMS','SCOTT'));

6. SELECT DEPTNO
 FROM EMP
 WHERE ENAME LIKE '%A%' AND ENAME LIKE '%S%'
 GROUP BY DEPTNO
 HAVING COUNT(*)>3;

7. SELECT *
FROM EMP
WHERE SAL>(SELECT SAL
FROM EMP
WHERE ENAME='SMITH') AND SAL<(SELECT SAL
FROM EMP
WHERE ENAME='KING');



8.SELECT ENAME,HIREDATE
FROM EMP
WHERE ENAME LIKE '%S' AND HIREDATE>(SELECT HIREDATE
FROM EMP
WHERE ENAME = 'ADAMS');

9.SELECT ENAME,HIREDATE
FROM EMP
WHERE ENAME LIKE '%S' AND HIREDATE>(SELECT HIREDATE
FROM EMP
WHERE ENAME = 'JAMES');


10.SELECT ENAME
FROM EMP
WHERE DEPTNO=(SELECT DEPTNO
FROM EMP
WHERE ENAME='JAMES') AND SAL>(SELECT SAL
FROM EMP
WHERE ENAME='ADAMS') AND JOB=(SELECT JOB
FROM EMP
WHERE ENAME='MILLER') AND HIREDATE>(SELECT HIREDATE
FROM EMP
WHERE ENAME='MARTIN');
