Q1.WAQTD THE ANNUAL SALARY OF THE EMPLOYEE WHOS
NAME IS SMITH

1. SELECT ENAME SAL,SAL*12 ANUSAL
FROM EMP
WHERE ENAME='SMITH';

Q2.WAQTD NAME OF THE EMPLOYEES WORKING AS CLERK

2. SELECT*
  FROM EMP
  WHERE JOB='CLERK';

Q3.WAQTD SALARY OF THE EMPLOYEES WHO ARE
WORKING AS SALESMAN

3. SELECT ENAME ,SAL
FROM EMP
WHERE JOB='SALESMAN';

Q4.WAQTD DETAILS OF THE EMP WHO EARNS MORE THAN
2000

 4.SELECT*
 FROM EMP
 WHERE SAL>2000;

Q5.WAQTD DETAILS OF THE EMP WHOS NAME IS JONES.

 5. SELECT *
 FROM EMP
 WHERE ENAME='JONES';

Q6.WAQTD DETAILS OF THE EMP WHO WAS HIRED AFTER
01-JAN-81

6.SELECT*
  FROM EMP
  WHERE HIREDATE>'01-JAN-81';

Q7.WAQTD NAME AND SAL ALONG WITH HIS ANNUAL
SALARY IF THE ANNUAL SALARY IS MORE THAN 12000.

7.SELECT ENAME ,SAL,(SAL*12) AS ANNUALSALARY
 FROM EMP
 WHERE SAL*12>12000;

Q8.WAQTD EMPNO OF THE EMPLOYEES WHO ARE WORKING
IN DEPT 30 

8.SELECT EMPNO
  FROM EMP
   WHERE DEPTNO=30;

Q9.WAQTD ENAME AND HIREDATE IF THEY ARE HIRED
BEFORE 1981.

9.SELECT ENAME,HIREDATE
 FROM EMP
 WHERE HIREDATE<'01-JAN-81';

Q10.WAQTD DETAILS OF THE EMPLOYEES WORKING AS
MANAGER

10. SELECT *
     FROM EMP
    WHERE JOB ='MANAGER';

Q11.WAQTD NAME AND SALARY GIVEN TO AN EMPLOYEE IF
EMPLOYEE EARNS A COMMISSION OF RUPEES 1400.

11. 
SELECT ENAME,SAL
FROM EMP
WHERE COMM=1400;

Q12.WAQTD DETAILS OF EMPLOYEES HAVING COMMISSION
MORE THAN SALARY.

12.  SELECT *
    FROM EMP
     WHERE COMM>SAL;

Q13.WAQTD EMPNO OF EMPLOYEES HIRED BEFORE THE
YEAR 87.

13. 
SELECT EMPNO
FROM EMP
WHERE HIREDATE<'01-JAN-87';

Q14.WAQTD DETAILS OF EMPLOYEES WORKING AS AN N
ANALYST.

14.SELECT *
FROM EMP
WHERE JOB='ANALYST';

Q15.WAQTD DETAILS OF EMPS EARNING MORE THAN 2000
RUPEES PER MONTH 

15. SELECT *
    FROM EMP
     WHERE SAL > 2000;
